default:  fxctmp9_tmp\Water_ps20b.inc shaders\fxc\Water_ps20b.vcs fxctmp9_tmp\ae_colorgrade_ps20.inc shaders\fxc\ae_colorgrade_ps20.vcs fxctmp9_tmp\ae_filmgrain_ps20.inc shaders\fxc\ae_filmgrain_ps20.vcs fxctmp9_tmp\ae_lensflare_ps20b.inc shaders\fxc\ae_lensflare_ps20b.vcs fxctmp9_tmp\ae_lensflare_ps20.inc shaders\fxc\ae_lensflare_ps20.vcs fxctmp9_tmp\ae_outlinex_ps20.inc shaders\fxc\ae_outlinex_ps20.vcs fxctmp9_tmp\ae_outliney_ps20.inc shaders\fxc\ae_outliney_ps20.vcs fxctmp9_tmp\ae_screentension_ps20b.inc shaders\fxc\ae_screentension_ps20b.vcs fxctmp9_tmp\ae_ssao_ps20b.inc shaders\fxc\ae_ssao_ps20b.vcs fxctmp9_tmp\SDK_screenspaceeffect_vs20.inc shaders\fxc\SDK_screenspaceeffect_vs20.vcs

fxctmp9_tmp\Water_ps20b.inc shaders\fxc\Water_ps20b.vcs: Water_ps2x.fxc ..\..\devtools\bin\updateshaders.pl ..\..\devtools\bin\fxc_prep.pl common_flashlight_fxc.h common_fog_ps_fxc.h common_vertexlitgeneric_dx9.h common_hlsl_cpp_consts.h common_fxc.h common_pragmas.h shader_constant_register_map.h common_ps_fxc.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." Water_ps2x.fxc-----Water_ps20b
	echo Water_ps2x.fxc>> filestocopy.txt
	echo common_flashlight_fxc.h>> filestocopy.txt
	echo common_fog_ps_fxc.h>> filestocopy.txt
	echo common_vertexlitgeneric_dx9.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo shader_constant_register_map.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt

fxctmp9_tmp\ae_colorgrade_ps20.inc shaders\fxc\ae_colorgrade_ps20.vcs: ae_colorgrade_ps20.fxc ..\..\devtools\bin\updateshaders.pl ..\..\devtools\bin\fxc_prep.pl common_ps_fxc.h common_pragmas.h common_fxc.h common_hlsl_cpp_consts.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." ae_colorgrade_ps20.fxc-----ae_colorgrade_ps20
	echo ae_colorgrade_ps20.fxc>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt

fxctmp9_tmp\ae_filmgrain_ps20.inc shaders\fxc\ae_filmgrain_ps20.vcs: ae_filmgrain_ps20.fxc ..\..\devtools\bin\updateshaders.pl ..\..\devtools\bin\fxc_prep.pl common_pragmas.h common_fxc.h common_hlsl_cpp_consts.h common_ps_fxc.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." ae_filmgrain_ps20.fxc-----ae_filmgrain_ps20
	echo ae_filmgrain_ps20.fxc>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt

fxctmp9_tmp\ae_lensflare_ps20b.inc shaders\fxc\ae_lensflare_ps20b.vcs: ae_lensflare_ps2x.fxc ..\..\devtools\bin\updateshaders.pl ..\..\devtools\bin\fxc_prep.pl common_ps_fxc.h common_fxc.h common_hlsl_cpp_consts.h common_pragmas.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." ae_lensflare_ps2x.fxc-----ae_lensflare_ps20b
	echo ae_lensflare_ps2x.fxc>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt

fxctmp9_tmp\ae_lensflare_ps20.inc shaders\fxc\ae_lensflare_ps20.vcs: ae_lensflare_ps20.fxc ..\..\devtools\bin\updateshaders.pl ..\..\devtools\bin\fxc_prep.pl common_pragmas.h common_hlsl_cpp_consts.h common_fxc.h common_ps_fxc.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." ae_lensflare_ps20.fxc-----ae_lensflare_ps20
	echo ae_lensflare_ps20.fxc>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt

fxctmp9_tmp\ae_outlinex_ps20.inc shaders\fxc\ae_outlinex_ps20.vcs: ae_outlinex_ps20.fxc ..\..\devtools\bin\updateshaders.pl ..\..\devtools\bin\fxc_prep.pl common_ps_fxc.h common_pragmas.h common_fxc.h common_hlsl_cpp_consts.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." ae_outlinex_ps20.fxc-----ae_outlinex_ps20
	echo ae_outlinex_ps20.fxc>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt

fxctmp9_tmp\ae_outliney_ps20.inc shaders\fxc\ae_outliney_ps20.vcs: ae_outliney_ps20.fxc ..\..\devtools\bin\updateshaders.pl ..\..\devtools\bin\fxc_prep.pl common_ps_fxc.h common_pragmas.h common_hlsl_cpp_consts.h common_fxc.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." ae_outliney_ps20.fxc-----ae_outliney_ps20
	echo ae_outliney_ps20.fxc>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt

fxctmp9_tmp\ae_screentension_ps20b.inc shaders\fxc\ae_screentension_ps20b.vcs: ae_screentension_ps20b.fxc ..\..\devtools\bin\updateshaders.pl ..\..\devtools\bin\fxc_prep.pl common_ps_fxc.h common_fxc.h common_hlsl_cpp_consts.h common_pragmas.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." ae_screentension_ps20b.fxc-----ae_screentension_ps20b
	echo ae_screentension_ps20b.fxc>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt

fxctmp9_tmp\ae_ssao_ps20b.inc shaders\fxc\ae_ssao_ps20b.vcs: ae_ssao_ps20b.fxc ..\..\devtools\bin\updateshaders.pl ..\..\devtools\bin\fxc_prep.pl common_ps_fxc.h common_pragmas.h common_hlsl_cpp_consts.h common_fxc.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." ae_ssao_ps20b.fxc-----ae_ssao_ps20b
	echo ae_ssao_ps20b.fxc>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt

fxctmp9_tmp\SDK_screenspaceeffect_vs20.inc shaders\fxc\SDK_screenspaceeffect_vs20.vcs: SDK_screenspaceeffect_vs20.fxc ..\..\devtools\bin\updateshaders.pl ..\..\devtools\bin\fxc_prep.pl common_vs_fxc.h common_pragmas.h common_fxc.h common_hlsl_cpp_consts.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." SDK_screenspaceeffect_vs20.fxc-----SDK_screenspaceeffect_vs20
	echo SDK_screenspaceeffect_vs20.fxc>> filestocopy.txt
	echo common_vs_fxc.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt

