default:  fxctmp9_tmp\portal_ps30.inc shaders\fxc\portal_ps30.vcs fxctmp9_tmp\portal_vs30.inc shaders\fxc\portal_vs30.vcs fxctmp9_tmp\portal_refract_ps30.inc shaders\fxc\portal_refract_ps30.vcs fxctmp9_tmp\portal_refract_vs30.inc shaders\fxc\portal_refract_vs30.vcs fxctmp9_tmp\portalstaticoverlay_ps30.inc shaders\fxc\portalstaticoverlay_ps30.vcs fxctmp9_tmp\portalstaticoverlay_vs30.inc shaders\fxc\portalstaticoverlay_vs30.vcs

fxctmp9_tmp\portal_ps30.inc shaders\fxc\portal_ps30.vcs: portal_ps2x.fxc ..\..\devtools\bin\updateshaders.pl ..\..\devtools\bin\fxc_prep.pl shader_constant_register_map.h common_vertexlitgeneric_dx9.h common_hlsl_cpp_consts.h common_pragmas.h common_ps_fxc.h common_fxc.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." portal_ps2x.fxc-----portal_ps30
	echo portal_ps2x.fxc>> filestocopy.txt
	echo shader_constant_register_map.h>> filestocopy.txt
	echo common_vertexlitgeneric_dx9.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt

fxctmp9_tmp\portal_vs30.inc shaders\fxc\portal_vs30.vcs: portal_vs20.fxc ..\..\devtools\bin\updateshaders.pl ..\..\devtools\bin\fxc_prep.pl common_fxc.h common_vs_fxc.h common_hlsl_cpp_consts.h common_pragmas.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." portal_vs20.fxc-----portal_vs30
	echo portal_vs20.fxc>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_vs_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt

fxctmp9_tmp\portal_refract_ps30.inc shaders\fxc\portal_refract_ps30.vcs: portal_refract_ps2x.fxc ..\..\devtools\bin\updateshaders.pl ..\..\devtools\bin\fxc_prep.pl common_ps_fxc.h common_fxc.h common_pragmas.h common_hlsl_cpp_consts.h common_vertexlitgeneric_dx9.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." portal_refract_ps2x.fxc-----portal_refract_ps30
	echo portal_refract_ps2x.fxc>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_vertexlitgeneric_dx9.h>> filestocopy.txt

fxctmp9_tmp\portal_refract_vs30.inc shaders\fxc\portal_refract_vs30.vcs: portal_refract_vs20.fxc ..\..\devtools\bin\updateshaders.pl ..\..\devtools\bin\fxc_prep.pl common_fxc.h common_vs_fxc.h common_pragmas.h common_hlsl_cpp_consts.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." portal_refract_vs20.fxc-----portal_refract_vs30
	echo portal_refract_vs20.fxc>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_vs_fxc.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt

fxctmp9_tmp\portalstaticoverlay_ps30.inc shaders\fxc\portalstaticoverlay_ps30.vcs: portalstaticoverlay_ps2x.fxc ..\..\devtools\bin\updateshaders.pl ..\..\devtools\bin\fxc_prep.pl shader_constant_register_map.h common_fxc.h common_ps_fxc.h common_vertexlitgeneric_dx9.h common_hlsl_cpp_consts.h common_pragmas.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." portalstaticoverlay_ps2x.fxc-----portalstaticoverlay_ps30
	echo portalstaticoverlay_ps2x.fxc>> filestocopy.txt
	echo shader_constant_register_map.h>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_ps_fxc.h>> filestocopy.txt
	echo common_vertexlitgeneric_dx9.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt

fxctmp9_tmp\portalstaticoverlay_vs30.inc shaders\fxc\portalstaticoverlay_vs30.vcs: portalstaticoverlay_vs20.fxc ..\..\devtools\bin\updateshaders.pl ..\..\devtools\bin\fxc_prep.pl common_fxc.h common_vs_fxc.h common_hlsl_cpp_consts.h common_pragmas.h
	perl ..\..\devtools\bin\fxc_prep.pl   -source "..\.." portalstaticoverlay_vs20.fxc-----portalstaticoverlay_vs30
	echo portalstaticoverlay_vs20.fxc>> filestocopy.txt
	echo common_fxc.h>> filestocopy.txt
	echo common_vs_fxc.h>> filestocopy.txt
	echo common_hlsl_cpp_consts.h>> filestocopy.txt
	echo common_pragmas.h>> filestocopy.txt

